CREATE DATABASE IF NOT EXISTS wordpress;

GRANT ALL PRIVILEGES ON wordpress.* TO "root"@"localhost" IDENTIFIED BY '=R4cine5007';
GRANT ALL PRIVILEGES ON phpmyadmin.* TO "root"@"localhost" IDENTIFIED BY '=R4cine5007';

FLUSH PRIVILEGES;
